### ISSUE TITLE
How to install + can it be dual-booted?

### ISSUE THREAD

**Issue by Viswas-Programs** [Killaship/yetanotherOS#1]
The title explains it
Can I dual boot the OS and does it even have a boot manager or it's using GRUB?

**Comment by Killaship** [comment]
Hello! Currently, it's not much of a functioning OS, but what you have to do is build the OS, and either run the OS on a virtual machine like QEMU or VirtualBox, or burn it to a drive or CD and boot it.
It uses GRUB, but I don't remember if it has the boot menu, it might just boot to the OS.
In any case, you can run the OS in a VM, but it doesn't currently have the functionality to _install_ to a drive.

You can definitely dual boot it if you were to add a partition or something to your current drive, add the image to GRUB's menu with some fiddling around with the config options, and boot to it. Not sure if you'd want to, though, it's much easier to work on the bot via a VM.
If you build and run the OS, or at least the version I currently have for development, this repository isn't updated anymore, see the screenshot I attached. The "shell" doesn't do anything.  :p
In any case, thanks for asking! It's pretty cool seeing people interested in my OS!
<img width="960" alt="image" src="https://user-images.githubusercontent.com/69988679/227809351-302944fa-f4a2-41a4-ae2b-f8f49cc68e24.png">

**Comment by Viswas-Programs** [comment]
Ok then what's a updated version of your OS that I can triple-boot with
and will this be detected automatically with Windows Boot Manager too? or only grub?

**Comment by Killaship** [comment]
I'm not sure if it'll be automatically detected. It probably won't, it's meant for you to plop it on a CD and go. In any case, if you're planning to try my OS, do it in a virtual machine, I personally wouldn't recommend real hardware, it's barely even designed for modern hardware.
I'll add an OS image to the repository, you can try that. It's not of any function and it's basically a demo of booting and the keyboard, but it's something!
(hey, if something crashes, at least I focused on error tracing, lol)
